version: "3.8"  

services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mysql://root:mypassword@mysql:3306/mydatabase 
    depends_on:
      - redis
      - mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword  
      MYSQL_DATABASE: mydatabase  
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword  
    ports:
      - "3307:3306"  
